/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorVentana;
import Modelo.Hilo;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class FRM_Principal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Principal
     */
      private ArrayList<JLabel> listaElementos;
      private Random numAleatorios;
      private  Hilo hilo;
      private int sumatoria;
      private  Controlador.ControladorVentana controlador;
    public FRM_Principal() {
        initComponents();
        this.setSize(670, 463);
      
        numAleatorios = new Random();
        listaElementos= new ArrayList<>();
        llenarListaElementos();
        estadoInicialJlabel();
        controlador= new ControladorVentana(this);
        sumatoria=0;
        escuchaItems(controlador);
    }

    public void escuchaItems(ActionListener actionListener)
    {
        jMNuevo.addActionListener(actionListener);
        jMSalir.addActionListener(actionListener);
        jMMejorPuntaje.addActionListener(actionListener);
        jMPeorPuntaje.addActionListener(actionListener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCarro = new javax.swing.JLabel();
        jLFruta2 = new javax.swing.JLabel();
        jLFruta1 = new javax.swing.JLabel();
        jLPuntos = new javax.swing.JLabel();
        jLImagenTime = new javax.swing.JLabel();
        jLTime = new javax.swing.JLabel();
        jLObtaculo = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMNuevo = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMMejorPuntaje = new javax.swing.JMenuItem();
        jMPeorPuntaje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 400));
        setPreferredSize(new java.awt.Dimension(660, 400));
        setType(java.awt.Window.Type.POPUP);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carretillo2.png"))); // NOI18N
        getContentPane().add(jLCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 60, 50));

        jLFruta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panda.gif"))); // NOI18N
        getContentPane().add(jLFruta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLFruta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manzana.png"))); // NOI18N
        getContentPane().add(jLFruta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 30));

        jLPuntos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLPuntos.setForeground(new java.awt.Color(255, 0, 0));
        jLPuntos.setText("Pts");
        getContentPane().add(jLPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, -1));

        jLImagenTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        getContentPane().add(jLImagenTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        jLTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLTime.setForeground(new java.awt.Color(255, 0, 0));
        jLTime.setText("TIME");
        getContentPane().add(jLTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 20));

        jLObtaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rocka.png"))); // NOI18N
        getContentPane().add(jLObtaculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 60, 50));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noche2.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        jMenu1.setText("Juego");

        jMNuevo.setText("Nuevo");
        jMenu1.add(jMNuevo);

        jMSalir.setText("Salir");
        jMenu1.add(jMSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMMejorPuntaje.setText("Mejor Puntaje");
        jMenu2.add(jMMejorPuntaje);

        jMPeorPuntaje.setText("Peor Puntaje");
        jMenu2.add(jMPeorPuntaje);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.err.println(""+evt.getKeyCode());
        if(evt.getKeyCode()==KeyEvent.VK_LEFT)
        {
           moverBarrilIzquierda();
        }
        if(evt.getKeyCode()==KeyEvent.VK_RIGHT)
        {
           moverBarrilDerecha();
        }
        if(evt.getKeyCode()==38)
        {
            moverBarriArriba();
        }
        if(evt.getKeyCode()==40)
        {
          moverHaciaBajo();
        }
    }//GEN-LAST:event_formKeyPressed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Principal().setVisible(true);
            }
        });
    }

        public void moverBarrilDerecha() {
        
      if((jLCarro.getX()>240&&jLCarro.getX()<335)&&jLCarro.getY()>308)
      {
          jLObtaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Erase.png"))); 
      }
      else
      {
           jLObtaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rocka.png"))); 
            if (jLCarro.getLocation().getX() < 580) 
            {
                jLCarro.setLocation(jLCarro.getX() + 20, jLCarro.getY());
                jLCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carretillo2.png"))); 
             }
      }    
    }
        
        public void moverHaciaBajo()
    {   
        if(jLCarro.getX()>260&&jLCarro.getX()<335&& jLCarro.getY()>290)
            {
                    jLObtaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Erase.png"))); 
            }
            else
            {
                jLObtaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rocka.png"))); 
                if (jLCarro.getLocation().getY() < 340) 
                {
                    jLCarro.setLocation(jLCarro.getX(), jLCarro.getY()+20);
                }  
            }
    }

        public void moverBarrilIzquierda() 
    {
        if((jLCarro.getX()<362&&jLCarro.getX()>300)&&jLCarro.getY()>308)
      {
         jLObtaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Erase.png"))); 
      }
        else
        {
             jLObtaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rocka.png"))); 
            if (jLCarro.getLocation().getX() > 10) 
            {
                jLCarro.setLocation(jLCarro.getX() -20, jLCarro.getY());
                jLCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carretillo2Volteadoo.png"))); 
            } 
        }
    }
      public void moverBarriArriba() {
        if (jLCarro.getLocation().getY() > 250) 
        {
             jLObtaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rocka.png"))); 
            jLCarro.setLocation(jLCarro.getX(), jLCarro.getY()-20);
        }
      }
    
     
    public int generarAletorio1()
    {
        return (int) (numAleatorios.nextDouble() *600 + 10);
       
    }
    public int generarAleatorio2()
    {
        return (int) (numAleatorios.nextDouble() *600 + 10);
    }
    
       public void llenarListaElementos() {
        //Escrementos
        listaElementos.add(0,jLFruta1);
        listaElementos.add(1, jLFruta2);       
    }
    
    public void estadoInicialJlabel() {    
        jLFruta2.setVisible(false);
        jLFruta1.setVisible(false);
    }
    
    
      
   public void mover ()
   {
       listaElementos.get(0).setVisible(true);
       listaElementos.get(1).setVisible(true);

       listaElementos.get(0).setLocation(listaElementos.get(0).getX(), listaElementos.get(0).getY()+6);
       listaElementos.get(1).setLocation(listaElementos.get(1).getX(), listaElementos.get(1).getY()+4);
       if(listaElementos.get(0).getY()>450)
       {
          listaElementos.get(0).setLocation(generarAletorio1(), 50);
       }
        if(listaElementos.get(1).getY()>450)
       {
          listaElementos.get(1).setLocation(generarAleatorio2(), 50);
       }            
   }
     public void cambiarNumero(int numero)
   {
       jLImagenTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+numero+".png"))); 
   }
    public void atraparObjetos()
    {
        if(listaElementos.get(0).getX()>=jLCarro.getX()-20&&listaElementos.get(0).getX()<jLCarro.getX()+35)
        {
            if(listaElementos.get(0).getY()>=jLCarro.getY()-15&&listaElementos.get(0).getY()<jLCarro.getY()+10)
            {
                listaElementos.get(0).setLocation(listaElementos.get(0).getX(),450);
                 sumatoria+=5;
                 repaint();
            }
        }
          if(listaElementos.get(1).getX()>=jLCarro.getX()-20&&listaElementos.get(1).getX()<jLCarro.getX()+35)
        {
            if(listaElementos.get(1).getY()>=jLCarro.getY()-20&&listaElementos.get(1).getY()<jLCarro.getY()+10)
            {
               
                listaElementos.get(1).setLocation(listaElementos.get(1).getX(),450);
                sumatoria+=5;
                repaint();
            }
        }
          
          
    }

   
    public void paint (Graphics g)
    {
        super.paint(g);  
        g.setColor((new java.awt.Color(51, 255, 204)));
        g.drawString(""+sumatoria, 635, 100);

    }
    
    
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(this,mensaje);
    }
    public int getTotalPuntos()
    {
        return  sumatoria;
    }
    public void nuevoJuego()
    {
        hilo= new Hilo(this);
        hilo.start();
        desHabilitarOpciones();
    }
    public void desHabilitarOpciones()
    {
        jMMejorPuntaje.setEnabled(false);
        jMPeorPuntaje.setEnabled(false);
        jMNuevo.setEnabled(false);
    }
     public void habilitarOpciones()
    {
        jMMejorPuntaje.setEnabled(true);
        jMPeorPuntaje.setEnabled(true);
        jMNuevo.setEnabled(true);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCarro;
    private javax.swing.JLabel jLFruta1;
    private javax.swing.JLabel jLFruta2;
    private javax.swing.JLabel jLImagenTime;
    private javax.swing.JLabel jLObtaculo;
    private javax.swing.JLabel jLPuntos;
    private javax.swing.JLabel jLTime;
    private javax.swing.JMenuItem jMMejorPuntaje;
    private javax.swing.JMenuItem jMNuevo;
    private javax.swing.JMenuItem jMPeorPuntaje;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables


}
